version: '3'

services:
  postgres:
    image: postgres:16.1
    container_name: leads_db
    environment:
      POSTGRES_DB: leads_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    build: .
    container_name: leads_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
        DB_HOST: "postgres"
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        SERPAPI_API_KEY: ${SERPAPI_API_KEY}
